java-microservice:
  name: scatterer
  partOf: scatter-gather
  replicas: 1

  kafka:
    bootstrapServer: kafka-bridge:9092

  container:
    port: 8080
    portName: scatterer-port
    image:
      name: ssj256x/scatterer
      tag: 0.0.1

  ingress:
    enabled: true
    host: scatterer.192.168.1.13.sslip.io

  service:
    enabled: true
    port: 80