apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
  labels:
    app: {{ .Release.Name }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    app.kubernetes.io/component: network-bridge
spec:
  type: ExternalName
  externalName: {{ .Values.kafka.externalName }}
