management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://tempo:4318/v1/traces

  endpoints:
    web:
      exposure:
        include: health,info,prometheus