apiVersion: v1
kind: Service
metadata:
  name: scatter-gather-kafka-bootstrap
  namespace: default
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: network-bridge
spec:
  type: ExternalName
  externalName: {{ .Values.kafka.externalName }}
