apiVersion: v2
name: scatterer
version: 1.0.0
description: > 
  A simple Java Microservice that consumes batches from the scatterer microservice, processes them and 
  publishes them to Kafka.
appVersion: "0.0.1"
keywords:
  - java
  - microservice
  - scatter-gather
  - kafka-consumer
dependencies:
  - name: java-microservice
    version: 0.0.1
    repository: file://../java-microservice