java-microservice:
  name: worker
  partOf: scatter-gather
  replicas: 1

  kafka:
    bootstrapServer: scatter-gather-kafka-bootstrap:9092

  container:
    port: 8080
    portName: worker-port
    image:
      name: ssj256x/worker
      tag: 0.0.1

  ingress:
    enabled: false
    host: worker.192.168.1.13.sslip.io

  service:
    enabled: false
    port: 80