apiVersion: v2
name: gatherer
version: 1.0.0
description: A simple Java Microservice that aggregates data from Kafka and publishes them to a Kafka topic.
appVersion: "0.0.1"
keywords:
  - java
  - microservice
  - scatter-gather
  - kafka-consumer
dependencies:
  - name: java-microservice
    version: 0.0.1
    repository: file://../java-microservice