java-microservice:
  name: gatherer
  partOf: scatter-gather
  replicas: 1

  kafka:
    bootstrapServer: scatter-gather-kafka-bootstrap:9092

  container:
    port: 8080
    portName: gatherer-port
    image:
      name: ssj256x/gatherer
      tag: 0.0.1

  ingress:
    enabled: false
    host: gatherer.192.168.1.13.sslip.io

  service:
    enabled: false
    port: 80